// ignore_for_file: non_constant_identifier_names, unused_local_variable

class BottomContent {
  static List<Map<String, String>> search_page_img() {
    return [
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOZuSoOpuJGwpRwdrd1PSxFdT9jKUs5s_IsQ&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAwIwB4AGz6m0ansF8-ilMRHme7v8-SINA9w&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkiiCANFl9TS-di9pg6QfI54FoNt_aeOcYhA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLYtqGdbw4Bfpsg1iCjKfyqthrq8z-M19FuQ&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDrmVmKhMT5vcDhzSGbLxazrpkSI3g6D1QiA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_tpPjdh8FFfGaJf8r0zeHwji3isAnswZdBA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSATaYfrQuBVlckOI80aHF6X17DnUUQFZRJJg&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSsgeO85YpilDSdT_dHACNHM6uglAHJ2xGrEg&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ft325Sxt60EDIWDZvFb6tyJMIOo7WbkeAQ&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcFNus3XyG9w64o3gaEqoWl-9IkZoBet-7Iw&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOZuSoOpuJGwpRwdrd1PSxFdT9jKUs5s_IsQ&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAwIwB4AGz6m0ansF8-ilMRHme7v8-SINA9w&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTkiiCANFl9TS-di9pg6QfI54FoNt_aeOcYhA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLYtqGdbw4Bfpsg1iCjKfyqthrq8z-M19FuQ&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDrmVmKhMT5vcDhzSGbLxazrpkSI3g6D1QiA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_tpPjdh8FFfGaJf8r0zeHwji3isAnswZdBA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSATaYfrQuBVlckOI80aHF6X17DnUUQFZRJJg&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOyhtT5U7hvxXtp2dZKw_BWKwjj1eGWh2WiA&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy9qqf3N5uQ-ZRoiDHmH7k1NkYK1GqtYevHSKkIhKEFXD2e-wYd8o44C1JAq0FbpYjU20&usqp=CAU",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3kNdAOI0Q4aEawtVpRk-VxiEdiDudL9yYjQ&s",
      },
      {
        "img":
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDvFFaUpn8bcVHvoqZBgDr_p5N28kP5xn0Vg&s",
      },
    ];
  }
}
